services:
  web-hook:
    build:
      context: .
      dockerfile: ./ucode_webhook/.dockerfile
    working_dir: /app/ucode_webhook
    ports:
      - "5001:5001"
    env_file:
      - ./ucode_webhook/.env
      - .env
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_RAW_EVENTS_TOPIC: "raw_events"
    volumes:
      - .:/app
    depends_on:
      kafka-setup:
        condition: service_completed_successfully
    command:
      [
        "sh",
        "-c",
        "python manage.py migrate && python manage.py runserver 0.0.0.0:5001",
      ]
    container_name: web-hook

  core-service-worker:
    build:
      context: .
      dockerfile: ./ucode_webhook/.dockerfile
    working_dir: /app/core_service
    env_file:
      - ./core_service/.env
      - .env
    environment:
      DJANGO_DEBUG: "1"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_RAW_EVENTS_TOPIC: "raw_events"
      KAFKA_SEND_FAILED_TOPIC: "send_failed"
      FACEBOOK_ACTIONS_ENABLED: "1"
    volumes:
      - .:/app
    depends_on:
      kafka-setup:
        condition: service_completed_successfully
    command:
      [
        "sh",
        "-c",
        "python manage.py migrate && python manage.py consume_raw_events",
      ]
    container_name: core-service-worker

  core-service-retry:
    build:
      context: .
      dockerfile: ./ucode_webhook/.dockerfile
    working_dir: /app/core_service
    env_file:
      - ./core_service/.env
      - .env
    environment:
      DJANGO_DEBUG: "1"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      FACEBOOK_ACTIONS_ENABLED: "1"
    volumes:
      - .:/app
    depends_on:
      kafka-setup:
        condition: service_completed_successfully
    command: ["sh", "-c", "python manage.py retry_failed_actions --sleep 2"]
    container_name: core-service-retry

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    container_name: kafka

  kafka-setup:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b kafka:9092 1 60 && \
                       kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic raw_events && \
                       kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic send_failed'"
    container_name: kafka-setup

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    container_name: kafka-ui
