# Generated by Django 6.0.4 on 2026-05-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('replied', 'Replied'), ('failed', 'Failed'), ('review_pending', 'Review Pending')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('spam_count_24h', models.IntegerField(default=0)),
                ('last_spam_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('action_payload', models.JSONField(default=dict)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_actions', to='app.incomingevent')),
            ],
        ),
        migrations.AddField(
            model_name='incomingevent',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socialprofile'),
        ),
    ]
